<?php
require_once DOC_ROOT . '/app/controllers/common/indexController.php';
require_once DOC_ROOT . '/app/controllers/common/blockController.php';
require_once DOC_ROOT . '/app/controllers/content/newsController.php';
require_once DOC_ROOT . '/app/controllers/content/serviceController.php';
require_once DOC_ROOT . '/app/controllers/content/contentController.php';
require_once DOC_ROOT . '/app/controllers/immovables/immovablesController.php';
require_once DOC_ROOT . '/app/controllers/immovables/buildingsController.php';
require_once DOC_ROOT . '/app/controllers/immovables/flatController.php';
require_once DOC_ROOT . '/app/controllers/immovables/landController.php';
require_once DOC_ROOT . '/app/controllers/immovables/homeController.php';
require_once DOC_ROOT . '/app/controllers/immovables/commercialController.php';
require_once DOC_ROOT . '/app/controllers/account/accountController.php';
require_once DOC_ROOT . '/app/controllers/immovables/reportController.php';