<?php
require_once DOC_ROOT . 'app/models/structure/model.php';
require_once DOC_ROOT . 'app/models/service/model.php';
require_once DOC_ROOT . 'app/models/partners/model.php';
require_once DOC_ROOT . 'app/models/immovables/model.php';
require_once DOC_ROOT . 'app/models/immovables/settings.php';
require_once DOC_ROOT . 'app/models/immovables/functions.php';
require_once DOC_ROOT . 'app/models/immovables/functionssearch.php';
require_once DOC_ROOT . 'app/models/immovables/searchmodel.php';
require_once DOC_ROOT . 'app/models/wiki/model.php';
require_once DOC_ROOT . 'app/models/sitemap/model.php';
require_once DOC_ROOT . 'app/models/vakansii/model.php';
/*require_once 'location/module.location.php';
require_once 'currency/module.currency.php';
require_once 'dictionary/module.dictionary.php';
require_once 'bookTour/module.book.tour.php';
require_once 'user/module.user.php';
require_once 'bill/module.bill.php';
require_once 'sitehelper/module.site.helper.php';
require_once 'basket/module.basket.php';
require_once 'company/module.company.php';
require_once 'advice/module.advice.php';
require_once 'message/module.message.php';
require_once 'banners/module.banners.php';
require_once 'rss/module.rss.php';*/