<?php
// список подлючаемых провайдеров (получение данных с БД, для моделей)
require_once DOC_ROOT . 'app/models/structure/provider.php';
require_once DOC_ROOT . 'app/models/service/provider.php';
require_once DOC_ROOT . 'app/models/partners/provider.php';
require_once DOC_ROOT . 'app/models/immovables/provider.php';
require_once DOC_ROOT . 'app/models/wiki/provider.php';
require_once DOC_ROOT . 'app/models/sitemap/provider.php';
require_once DOC_ROOT . 'app/models/vakansii/provider.php';
/*
require_once 'catalog/catalog.provider.php';
require_once 'content/content.provider.php';
require_once 'company/company.provider.php';
require_once 'advice/advice.provider.php';
require_once 'message/message.provider.php';
require_once 'banners/banners.provider.php';
require_once 'bill/bill.provider.php';
require_once 'user/user.provider.php';
require_once 'message/message.provider.php';
require_once 'vacancii/vacancii.provider.php';*/