<div class="eventForm">
<a href="#" onclick="TAddSpecialCode('DMN_Vacancii', 'getVacance');" class="ui-state-default ui-corner-all bottom-padding" title="Добавить вакансию" id="submitAdd"><span class="ui-icon ui-icon-plus"></span>Добавить вакансию</a> 
<!-- 
<a href="#" onclick="TAddSpecialCode('DMN_Places', 'getPlace');" class="ui-state-default ui-corner-all bottom-padding" title="редактировать пункт &laquo;Каталогa&raquo;" id="submitEdit"><span class="ui-icon ui-icon-pencil"></span>редактировать пункт</a> 
<a href="#" onclick="TAddSpecialCode('DMN_Places', 'dellPlace');" class="ui-state-default ui-corner-all bottom-padding" title="удалить пункт &laquo;Каталогa&raquo;" id="submitDell"><span class="ui-icon ui-icon-trash"></span>удалить пункт</a></div>
-->
</div>