<?php 
define ( 'SLASH', '/' );
define ( 'DOC_ROOT', $_SERVER ['DOCUMENT_ROOT'] );
require_once DOC_ROOT . '/dmn/utils/template.ajax/js2.css.php';
?>
<script type="text/javascript" src="../ReferenceCustomers/js/action.js"></script>
<div class="eventForm">
	<a href="#" onclick="TShowPage('DMN_ReferenceCustomers', 'getPage')" class="ui-state-default ui-corner-all bottom-padding" title="Назад" id=""><span class="ui-icon ui-icon-circle-triangle-w"></span>Назад</a> 
</div>
<div style="margin:0 10px 0 10px; padding:10px 0 0 0;">
	<div id='errOutputGood' class="errOutputGood"></div>
	<div id='errOutput' class="errOutput"></div>
	    	<script type="text/javascript">
				new Zapatec.Form({
					form: 'NewsForm',
					showErrors: 'afterField',
					showErrorsOnSubmit: true,
					submitErrorFunc: testErrOutput,
					asyncSubmitFunc: OnSuccessNewsForm,
					theme: "WinXP"
				});
			</script>
	 		<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_ReferenceCustomers&action=saveItem&dataType=json" id='NewsForm' name='NewsForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<label class='zpFormLabel'>ФИО</label> 
					<input class='zpFormRequired' value="<?php echo $Data ['rc_fio']; ?>" size="40" name="rc_fio" id="rc_fio" type="text"> <br />
					<label class='zpFormLabel'>Телефон</label> 
					<input class='zpFormRequired' value="<?php echo $Data ['rc_tel']; ?>" size="40" name="rc_tel" id="rc_tel" type="text"> <br />
					<label class='zpFormLabel'>Описание</label> <br />
					<textarea class='zpForm' rows="10" cols="10" name="rc_summary"><?php echo $Data ['rc_summary']; ?></textarea>
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Тип</label> 
					<select name="type_id" id="type_id"  class="zpFormRequired">
						<option value="">Не выбрано</option>
						<?php echo sel_parent_id ( $TypeDict, ($Data ['type_id'] ? $Data ['type_id'] : ""), 'dict_id', 'dict_name' ); ?>
					</select>
				</fieldset>
				<input class='zpForm' value="<?php echo $_COOKIE ['id_account']; ?>" size="13" name="user_id" type="hidden"> 
				<input class='zpForm' value="<?php echo ($Data ['rc_id'] ? $Data ['rc_id'] : "") ;?>" size="13" name="rc_id" type="hidden"> 
				<input class='zpForm' value="<?php echo ($Data ['rc_id'] ? "edit" : "new") ;?>" size="13" name="type_save" type="hidden"> 
				<input value="Сохранить" name="Submit" onClick="" type="submit" class="button" /> 
			</form>
	  </div>
</div>            

