<div class="DivHeaderMenuSearch">
	<p><?php echo $arWords['SearchImmovablesCodeText'];?></p>
	<form action="" id="im_code_form" name="im_code_form" enctype="application/x-www-form-urlencoded">
       	<input id="search_field" alt="" type="text" value="" name="id" />
		<input type="hidden" name="action" value="code" >
      	<a class="ui-state-default ui-corner-all AlinkSubmit" href="javascript:set_search_field();" title="<?php echo $arWords['SearchBottom'];?>" class="SearchFromBottom"><?php echo $arWords['SearchBottom'];?></a>
    </form>
</div>
