<?php
global $arWords;
/*
*		FLAT LIST PHOTO
*/
$ModuleTemplate ['ymaps'] ['4c3ec3ec5e9b5'] ['sale'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPrice\">#im_prices_ni#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderM2']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c4012253a36f#/#4c40122f31138# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c400ed4e5797#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderLavel']}:</span> #4c400ea1b5657#/#4c400ec87481e#</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/sale/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";
	
$ModuleTemplate ['ymaps'] ['4c3ec3ec5e9b5'] ['rent'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/rent/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/rent/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\" ><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPriceM\"><span>{$arWords['FormSearchNamePriceManth']} ($):</span> #im_prace_manth#</p><p class=\"yImPriceD\"><span>{$arWords['FormSearchNamePriceDay']} ($):</span> #im_prace_day#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderM2']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c4012253a36f#/#4c40122f31138# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c400ed4e5797#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderLavel']}:</span> #4c400ea1b5657#/#4c400ec87481e#</p></td></tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/flat/rent/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";

/*
*		COMMERCIAL LIST PHOTO
*/
$ModuleTemplate ['ymaps'] ['4c3ec3ec5e9b7'] ['sale'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPrice\">#im_prices_ni#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderM2']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c604016208bc# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c4050b294c4f#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderLavel']}:</span> #4c4050fc797b1#/#4c404804b576c#</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/sale/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";												

$ModuleTemplate ['ymaps'] ['4c3ec3ec5e9b7'] ['rent'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/rent/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/rent/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPriceM\"><span>{$arWords['FormSearchNamePriceManth']} ($):</span> #im_prace_manth#</p>															<p class=\"yImPriceD\"><span>{$arWords['FormSearchNamePriceDay']} ($):</span> #im_prace_day#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c604016208bc# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c4050b294c4f#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderLavel']}:</span> #4c4050fc797b1#/#4c404804b576c#</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/commercial/rent/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";
														
/*
*		HOME LIST PHOTO
*/
$ModuleTemplate ['ymaps'] ['4c3ec51d537c0'] ['sale'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPrice\">#im_prices_ni#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderM2']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c402f924bc2a# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c402f345c83d#</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/sale/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";

$ModuleTemplate ['ymaps'] ['4c3ec51d537c0'] ['rent']  = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/rent/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/rent/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPriceM\"><span>{$arWords['FormSearchNamePriceManth']} ($):</span> #im_prace_manth#</p><p class=\"yImPriceD\"><span>{$arWords['FormSearchNamePriceDay']} ($):</span> #im_prace_day#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c402f924bc2a# {$arWords['ImFListHeaderMapM2']}</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderRoom']}:</span> #4c402f345c83d#</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/rent/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";
														
/*
*		BUILDINGS LIST PHOTO
*/
$ModuleTemplate ['ymaps'] ['4c3ec51d537c2'] ['sale'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/buildings/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/buildings/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPrice\">#im_prices_ni#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderM2']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c40586e48e5f# {$arWords['ImFListHeaderMapM2']}</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/buildings/sale/1/#im_id#.html\">&nbsp;{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\">&nbsp;{$arWords[viewImYPanorama]}</a></td></tr></table>";

$ModuleTemplate ['ymaps'] ['4c3ec51d537c2'] ['rent'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/home/buildings/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/buildings/rent/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPriceM\"><span>{$arWords['FormSearchNamePriceManth']} ($):</span> #im_prace_manth#</p><p class=\"yImPriceD\"><span>{$arWords['FormSearchNamePriceDay']} ($):</span> #im_prace_day#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space#/#4c40586e48e5f# {$arWords['ImFListHeaderMapM2']}</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/buildings/rent/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";
											
/*
*		LAND LIST PHOTO
*/
$ModuleTemplate ['ymaps'] ['4c3ec51d537c3'] ['sale'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p>															<p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPrice\">#im_prices_ni#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSotku']}:</span> #im_prace_sq#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space# {$arWords['ImFListHeaderMapSotka']}</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";
$ModuleTemplate ['ymaps'] ['4c3ec51d537c3'] ['rent'] = "<table class=\"yTable\"><tr><td colspan=\"2\"><a class=\"yImTitle\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\">#im_title#</a></td></tr><tr><td class=\"yTableTdImg\"><a class=\"yImImg\" target=\"_blank\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\"><img src=\"{$arWords[imageDomain]}/files/images/immovables/si_#im_photo#\" alt=\"\"/></a></td><td class=\"yImProp\">#im_prop_list#</td></tr><tr><td colspan=\"2\"><p class=\"yImAdress\">#im_city_id# #im_adress_id# #im_adress_house# #im_adress_flat#</p>															<p class=\"yImSI\"><span>{$arWords['ImFListHeaderCodeN']}:</span> #im_code#</p><p class=\"yImPriceM\"><span>{$arWords['FormSearchNamePriceManth']} ($):</span> #im_prace_manth#</p><p class=\"yImSI\"><span>{$arWords['ImFListHeaderSqPl']}:</span> #im_space# {$arWords['ImFListHeaderMapSotka']}</p></td></tr><tr><td colspan=\"2\" class=\"yImLink\"><a target=\"_blank\" class=\"AYReadMore\" title=\"{$arWords[REadMoreInformation]}\" href=\"http://www.alfabrok.ua/ru/land/sale/1/#im_id#.html\"><span>&nbsp;</span>{$arWords[REadMoreInformation]}</a><a target=\"_blank\" class=\"AYPanorama\" title=\"{$arWords[viewImYPanorama]}\" href=\"hrefToPanorama\"><span>&nbsp;</span>{$arWords[viewImYPanorama]}</a></td></tr></table>";														
?>